#ifndef DSL_VARS_H
#define DSL_VARS_H

#include <string>
#include <map>
#include <stdexcept>

using std::runtime_error;
using std::string;


// typedef char16_t uc_char;
// typedef std::u16string uc_string;

typedef char32_t uc_char;
typedef std::u32string uc_string;
typedef string::size_type pos_t;


static const pos_t npos = string::npos;

enum Encoding {
  ENC_UTF16LE = 1,
  ENC_UTF8    = 2,
  ENC_UCS4LE  = 4,
};

namespace Vars {

static const char* DSL_ENCODING = "UTF-16LE";
static const char* DSL_ENCODING_UTF8 = "UTF-8";
static const char* DATA_ENCODING = "UCS-4LE";
static const char* STR_ENCODING = "UTF-8";

static const string ERROR_BTREE_DECOMPRESS_NODE = "Error decompressing B-tree node";
static const string ERROR_BTREE_COMPRESS_NODE = "Error compressing B-tree node";
static const string ERROR_BTREE_CORRUPT_LEAF = "Corrupted chain data in a B-tree leaf";
static const string ERROR_INDEX_NOT_OPENED = "Index not opened";
static const string ERROR_CONVERT_STRING = "Error converting string";
static const string ERROR_DECOMPRESS_CHUNK = "Error decompressing chunk";
static const string ERROR_COMPRESS_CHUNK = "Error compressing chunk";
static const string ERROR_CHUNK_ADDRESS_OUT_OF_RANGE = "Chunked address out of range";
static const string ERROR_CANNOT_OPEN_FILE = "Cannot open file";
static const string ERROR_READ_FILE = "Error reading file";
static const string ERROR_CANNOT_OPEN_DSL_FILE = "Cannot open DSL file";
static const string ERROR_READ_DSL_FILE = "Error reading DSL file";
static const string ERROR_INCORRECT_DSL_FILE = "Incorrect DSL file";
static const string ERROR_DSL_ENCODING = "Cannot determine DSL file encoding";
static const string ERROR_DICTZIP = "Dictzip error";

struct DslLang {
  unsigned code;
  char codeStr[4];
};

static std::map<uc_string, DslLang> langMap = {
  { U"Abazin", DslLang{1555, "--"} },
  { U"Abkhaz", DslLang{1556, "Ab"} },
  { U"Adyghe", DslLang{1557, "Ady"} },
  { U"Afrikaans", DslLang{1078, "Af"} },
  { U"Agul", DslLang{1559, "--"} },
  { U"Albanian", DslLang{1052, "Sq"} },
  { U"Altaic", DslLang{1545, "Tut"} },
  { U"Arabic", DslLang{1025, "Ar"} },
  { U"ArabicAlgeria", DslLang{5121, "Ar"} },
  { U"ArabicBahrain", DslLang{15361, "Ar"} },
  { U"ArabicEgypt", DslLang{3073, "Ar"} },
  { U"ArabicIraq", DslLang{2049, "Ar"} },
  { U"ArabicJordan", DslLang{11265, "Ar"} },
  { U"ArabicKuwait", DslLang{13313, "Ar"} },
  { U"ArabicLebanon", DslLang{12289, "Ar"} },
  { U"ArabicLibya", DslLang{4097, "Ar"} },
  { U"ArabicMorocco", DslLang{6145, "Ar"} },
  { U"ArabicOman", DslLang{8193, "Ar"} },
  { U"ArabicQatar", DslLang{16385, "Ar"} },
  { U"ArabicSaudiArabia", DslLang{1025, "Ar"} },
  { U"ArabicSyria", DslLang{10241, "Ar"} },
  { U"ArabicTunisia", DslLang{7169, "Ar"} },
  { U"ArabicUAE", DslLang{14337, "Ar"} },
  { U"ArabicYemen", DslLang{9217, "Ar"} },
  { U"Armenian", DslLang{1067, "Hy"} },
  { U"ArmenianEastern", DslLang{1067, "Hy"} },
  { U"ArmenianGrabar", DslLang{33835, "Hy"} },
  { U"ArmenianWestern", DslLang{32811, "Hy"} },
  { U"Assamese", DslLang{1101, "As"} },
  { U"Awar", DslLang{1558, "--"} },
  { U"Aymara", DslLang{1560, "Ay"} },
  { U"AzeriCyrillic", DslLang{2092, "Az"} },
  { U"AzeriLatin", DslLang{1068, "Az"} },
  { U"Bashkir", DslLang{1561, "Ba"} },
  { U"Basque", DslLang{1069, "Eu"} },
  { U"Belarusian", DslLang{1059, "Be"} },
  { U"Bemba", DslLang{1562, "Bem"} },
  { U"Bengali", DslLang{1093, "Bn"} },
  { U"Blackfoot", DslLang{1563, "--"} },
  { U"Breton", DslLang{1536, "Br"} },
  { U"Bugotu", DslLang{1564, "--"} },
  { U"Bulgarian", DslLang{1026, "Bg"} },
  { U"Burmese", DslLang{1109, "My"} },
  { U"Buryat", DslLang{1565, "--"} },
  { U"Byelorussian", DslLang{1059, "Be"} },
  { U"Catalan", DslLang{1027, "Ca"} },
  { U"Chamorro", DslLang{1566, "Ch"} },
  { U"Chechen", DslLang{1544, "Ce"} },
  { U"Chinese", DslLang{1028, "Zh"} },
  { U"ChineseHongKong", DslLang{3076, "Zh"} },
  { U"ChineseMacau", DslLang{5124, "Zh"} },
  { U"ChinesePRC", DslLang{2052, "Zh"} },
  { U"ChineseSingapore", DslLang{4100, "Zh"} },
  { U"ChineseTaiwan", DslLang{1028, "Zh"} },
  { U"Chuana", DslLang{1074, "Tn"} },
  { U"Chukcha", DslLang{1567, "--"} },
  { U"Chuvash", DslLang{1568, "Cv"} },
  { U"Corsican", DslLang{1569, "Co"} },
  { U"CrimeanTatar", DslLang{1546, "Crh"} },
  { U"Croatian", DslLang{1050, "Hr"} },
  { U"Crow", DslLang{1570, "--"} },
  { U"Czech", DslLang{1029, "Cs"} },
  { U"Dakota", DslLang{1632, "Dak"} },
  { U"Danish", DslLang{1030, "Da"} },
  { U"Dargin", DslLang{1571, "--"} },
  { U"Dargwa", DslLang{1571, "Dar"} },
  { U"Dungan", DslLang{1572, "--"} },
  { U"Dutch", DslLang{1043, "Nl"} },
  { U"DutchBelgian", DslLang{2067, "Nl"} },
  { U"DutchStandard", DslLang{1043, "Nl"} },
  { U"English", DslLang{1033, "En"} },
  { U"EnglishAustralian", DslLang{3081, "En"} },
  { U"EnglishBelize", DslLang{10249, "En"} },
  { U"EnglishCanadian", DslLang{4105, "En"} },
  { U"EnglishCaribbean", DslLang{9225, "En"} },
  { U"EnglishIreland", DslLang{6153, "En"} },
  { U"EnglishJamaica", DslLang{8201, "En"} },
  { U"EnglishLaw", DslLang{35849, "En"} },
  { U"EnglishMedical", DslLang{33801, "En"} },
  { U"EnglishNewZealand", DslLang{5129, "En"} },
  { U"EnglishPhilippines", DslLang{13321, "En"} },
  { U"EnglishProperNames", DslLang{34825, "En"} },
  { U"EnglishSouthAfrica", DslLang{7177, "En"} },
  { U"EnglishTrinidad", DslLang{11273, "En"} },
  { U"EnglishUnitedKingdom", DslLang{2057, "En"} },
  { U"EnglishUnitedStates", DslLang{1033, "En"} },
  { U"EnglishZimbabwe", DslLang{12297, "En"} },
  { U"EskimoCyrillic", DslLang{1573, "Iu"} },
  { U"EskimoLatin", DslLang{1581, "Iu"} },
  { U"Esperanto", DslLang{1537, "Eo"} },
  { U"Estonian", DslLang{1061, "Et"} },
  { U"Even", DslLang{1574, "--"} },
  { U"Evenki", DslLang{1575, "--"} },
  { U"Faeroese", DslLang{1080, "Fo"} },
  { U"Faroese", DslLang{1080, "Fo"} },
  { U"Farsi", DslLang{1065, "Fa"} },
  { U"Fijian", DslLang{1538, "Fj"} },
  { U"Finnish", DslLang{1035, "Fi"} },
  { U"Flemish", DslLang{2067, "Nl"} },
  { U"French", DslLang{1036, "Fr"} },
  { U"FrenchBelgian", DslLang{2060, "Fr"} },
  { U"FrenchCanadian", DslLang{3084, "Fr"} },
  { U"FrenchLuxembourg", DslLang{5132, "Fr"} },
  { U"FrenchMonaco", DslLang{6156, "Fr"} },
  { U"FrenchProperNames", DslLang{33804, "Fr"} },
  { U"FrenchStandard", DslLang{1036, "Fr"} },
  { U"FrenchSwiss", DslLang{4108, "Fr"} },
  { U"Frisian", DslLang{1122, "Fy"} },
  { U"Frisian_Legacy", DslLang{1576, "Fy"} },
  { U"Friulian", DslLang{1577, "Fur"} },
  { U"Gaelic", DslLang{2108, "Gd"} },
  { U"GaelicScottish", DslLang{1084, "Gd"} },
  { U"Gaelic_Legacy", DslLang{1552, "Gd"} },
  { U"Gagauz", DslLang{1578, "--"} },
  { U"Galician", DslLang{1110, "Gl"} },
  { U"Galician_Legacy", DslLang{1579, "Gl"} },
  { U"Ganda", DslLang{1580, "Lg"} },
  { U"Georgian", DslLang{1079, "Ka"} },
  { U"German", DslLang{1031, "De"} },
  { U"GermanAustrian", DslLang{3079, "De"} },
  { U"GermanLaw", DslLang{34823, "De"} },
  { U"GermanLiechtenstein", DslLang{5127, "De"} },
  { U"GermanLuxembourg", DslLang{4103, "De"} },
  { U"GermanMedical", DslLang{36871, "De"} },
  { U"GermanNewSpelling", DslLang{32775, "De"} },
  { U"GermanNewSpellingLaw", DslLang{35847, "De"} },
  { U"GermanNewSpellingMedical", DslLang{37895, "De"} },
  { U"GermanNewSpellingProperNames", DslLang{39943, "De"} },
  { U"GermanProperNames", DslLang{38919, "De"} },
  { U"GermanStandard", DslLang{1031, "De"} },
  { U"GermanSwiss", DslLang{2055, "De"} },
  { U"Greek", DslLang{1032, "El"} },
  { U"GreekKathareusa", DslLang{32776, "El"} },
  { U"Greenlandic", DslLang{1581, "Kl"} },
  { U"Guarani", DslLang{1140, "Gn"} },
  { U"Guarani_Legacy", DslLang{1582, "Gn"} },
  { U"Gujarati", DslLang{1095, "Gu"} },
  { U"Hani", DslLang{1583, "--"} },
  { U"Hausa", DslLang{1128, "Ha"} },
  { U"Hausa_Legacy", DslLang{1652, "Ha"} },
  { U"Hawaiian", DslLang{1141, "Haw"} },
  { U"Hawaiian_Legacy", DslLang{1539, "Haw"} },
  { U"Hebrew", DslLang{1037, "He"} },
  { U"Hindi", DslLang{1081, "Hi"} },
  { U"Hungarian", DslLang{1038, "Hu"} },
  { U"Icelandic", DslLang{1039, "Is"} },
  { U"Ido", DslLang{1584, "Io"} },
  { U"Indonesian", DslLang{1057, "Id"} },
  { U"Ingush", DslLang{1585, "Inh"} },
  { U"Interlingua", DslLang{1586, "Ia"} },
  { U"Irish", DslLang{2108, "Ga"} },
  { U"Irish_Legacy", DslLang{1552, "Ga"} },
  { U"Italian", DslLang{1040, "It"} },
  { U"ItalianProperNames", DslLang{33808, "It"} },
  { U"ItalianStandard", DslLang{1040, "It"} },
  { U"ItalianSwiss", DslLang{2064, "It"} },
  { U"Japanese", DslLang{1041, "Ja"} },
  { U"Kabardian", DslLang{1548, "Kbd"} },
  { U"Kachin", DslLang{1640, "Kac"} },
  { U"Kalmyk", DslLang{1587, "Xal"} },
  { U"Kannada", DslLang{1099, "Kn"} },
  { U"KarachayBalkar", DslLang{1589, "--"} },
  { U"Karakalpak", DslLang{1588, "--"} },
  { U"Kashmiri", DslLang{1120, "Ks"} },
  { U"KashmiriIndia", DslLang{2144, "Ks"} },
  { U"Kasub", DslLang{1590, "--"} },
  { U"Kawa", DslLang{1591, "--"} },
  { U"Kazakh", DslLang{1087, "Kk"} },
  { U"Khakas", DslLang{1592, "--"} },
  { U"Khanty", DslLang{1593, "--"} },
  { U"Khmer", DslLang{1107, "Km"} },
  { U"Kikuyu", DslLang{1594, "Ki"} },
  { U"Kirgiz", DslLang{1595, "Ky"} },
  { U"KomiPermian", DslLang{1597, "Kv"} },
  { U"KomiZyryan", DslLang{1596, "Kv"} },
  { U"Kongo", DslLang{1598, "Kg"} },
  { U"Konkani", DslLang{1111, "Kok"} },
  { U"Korean", DslLang{1042, "Ko"} },
  { U"KoreanJohab", DslLang{2066, "Ko"} },
  { U"Koryak", DslLang{1599, "--"} },
  { U"Kpelle", DslLang{1600, "Kpe"} },
  { U"Kumyk", DslLang{1601, "Kum"} },
  { U"Kurdish", DslLang{1602, "Ku"} },
  { U"KurdishCyrillic", DslLang{1603, "Ku"} },
  { U"Lak", DslLang{1604, "--"} },
  { U"Lao", DslLang{1108, "Lo"} },
  { U"Lappish", DslLang{1083, "--"} },
  { U"Latin", DslLang{1142, "La"} },
  { U"Latin_Legacy", DslLang{1540, "La"} },
  { U"Latvian", DslLang{1062, "Lv"} },
  { U"LatvianGothic", DslLang{1655, "Lv"} },
  { U"Lezgin", DslLang{1605, "--"} },
  { U"Lithuanian", DslLang{1063, "Lt"} },
  { U"LithuanianClassic", DslLang{2087, "Lt"} },
  { U"Luba", DslLang{1606, "Lu"} },
  { U"Macedonian", DslLang{1071, "Mk"} },
  { U"Malagasy", DslLang{1607, "Mg"} },
  { U"Malay", DslLang{1086, "Ms"} },
  { U"MalayBruneiDarussalam", DslLang{2110, "Ms"} },
  { U"MalayMalaysian", DslLang{1086, "Ms"} },
  { U"Malayalam", DslLang{1100, "Ml"} },
  { U"Malinke", DslLang{1608, "--"} },
  { U"Maltese", DslLang{1082, "Mt"} },
  { U"Manipuri", DslLang{1112, "Mni"} },
  { U"Mansi", DslLang{1609, "--"} },
  { U"Maori", DslLang{1153, "Mi"} },
  { U"Marathi", DslLang{1102, "Mr"} },
  { U"Mari", DslLang{1610, "Chm"} },
  { U"Maya", DslLang{1611, "Myn"} },
  { U"Miao", DslLang{1612, "--"} },
  { U"Minankabaw", DslLang{1613, "--"} },
  { U"Mohawk", DslLang{1614, "Moh"} },
  { U"Mongol", DslLang{1104, "Mn"} },
  { U"Mordvin", DslLang{1615, "--"} },
  { U"Nahuatl", DslLang{1616, "Nah"} },
  { U"Nanai", DslLang{1617, "--"} },
  { U"Nenets", DslLang{1618, "--"} },
  { U"Nepali", DslLang{1121, "Ne"} },
  { U"NepaliIndia", DslLang{2145, "Ne"} },
  { U"Nivkh", DslLang{1619, "--"} },
  { U"Nogay", DslLang{1620, "--"} },
  { U"Norwegian", DslLang{1044, "No"} },
  { U"NorwegianBokmal", DslLang{1044, "No"} },
  { U"NorwegianNynorsk", DslLang{2068, "No"} },
  { U"Nyanja", DslLang{1621, "Ny"} },
  { U"Occidental", DslLang{1622, "Ie"} },
  { U"Ojibway", DslLang{1623, "--"} },
  { U"OldEnglish", DslLang{32777, "En"} },
  { U"OldFrench", DslLang{32780, "Fr"} },
  { U"OldGerman", DslLang{33799, "De"} },
  { U"OldItalian", DslLang{32784, "It"} },
  { U"OldSlavonic", DslLang{1657, "Cu"} },
  { U"OldSpanish", DslLang{32778, "Es"} },
  { U"Oriya", DslLang{1096, "Or"} },
  { U"Ossetic", DslLang{1547, "Os"} },
  { U"Papiamento", DslLang{1145, "Pap"} },
  { U"Papiamento_Legacy", DslLang{1624, "Pap"} },
  { U"PidginEnglish", DslLang{1625, "En"} },
  { U"Pinyin", DslLang{1654, "--"} },
  { U"Polish", DslLang{1045, "Pl"} },
  { U"Portuguese", DslLang{1046, "Pt"} },
  { U"PortugueseBrazilian", DslLang{1046, "Pt"} },
  { U"PortugueseStandard", DslLang{2070, "Pt"} },
  { U"Provencal", DslLang{1541, "--"} },
  { U"Punjabi", DslLang{1094, "Pa"} },
  { U"Quechua", DslLang{1131, "Qu"} },
  { U"QuechuaBolivia", DslLang{1131, "Qu"} },
  { U"QuechuaEcuador", DslLang{2155, "Qu"} },
  { U"QuechuaPeru", DslLang{3179, "Qu"} },
  { U"Quechua_Legacy", DslLang{1626, "Qu"} },
  { U"RhaetoRomanic", DslLang{1047, "Rm"} },
  { U"Romanian", DslLang{1048, "Ro"} },
  { U"RomanianMoldavia", DslLang{2072, "Ro"} },
  { U"Romany", DslLang{1627, "Rom"} },
  { U"Ruanda", DslLang{1628, "--"} },
  { U"Rundi", DslLang{1629, "Rn"} },
  { U"Russian", DslLang{1049, "Ru"} },
  { U"RussianMoldavia", DslLang{2073, "Ru"} },
  { U"RussianOldOrtho", DslLang{34841, "Ru"} },
  { U"RussianOldSpelling", DslLang{32793, "Ru"} },
  { U"RussianProperNames", DslLang{33817, "Ru"} },
  { U"Saami", DslLang{1083, "--"} },
  { U"Samoan", DslLang{1542, "Sm"} },
  { U"Sanskrit", DslLang{1103, "Sa"} },
  { U"Selkup", DslLang{1630, "Sel"} },
  { U"SerbianCyrillic", DslLang{3098, "Sr"} },
  { U"SerbianLatin", DslLang{2074, "Sr"} },
  { U"Shona", DslLang{1631, "Sn"} },
  { U"Sindhi", DslLang{1113, "Sd"} },
  { U"Sioux", DslLang{1632, "--"} },
  { U"Slovak", DslLang{1051, "Sk"} },
  { U"Slovenian", DslLang{1060, "Sl"} },
  { U"Somali", DslLang{1143, "So"} },
  { U"Somali_Legacy", DslLang{1633, "So"} },
  { U"Sorbian", DslLang{1070, "Wen"} },
  { U"Sotho", DslLang{1634, "Nso"} },
  { U"Spanish", DslLang{1034, "Es"} },
  { U"SpanishArgentina", DslLang{11274, "Es"} },
  { U"SpanishBolivia", DslLang{16394, "Es"} },
  { U"SpanishChile", DslLang{13322, "Es"} },
  { U"SpanishColombia", DslLang{9226, "Es"} },
  { U"SpanishCostaRica", DslLang{5130, "Es"} },
  { U"SpanishDominicanRepublic", DslLang{7178, "Es"} },
  { U"SpanishEcuador", DslLang{12298, "Es"} },
  { U"SpanishElSalvador", DslLang{17418, "Es"} },
  { U"SpanishGuatemala", DslLang{4106, "Es"} },
  { U"SpanishHonduras", DslLang{18442, "Es"} },
  { U"SpanishMexican", DslLang{2058, "Es"} },
  { U"SpanishModernSort", DslLang{3082, "Es"} },
  { U"SpanishNicaragua", DslLang{19466, "Es"} },
  { U"SpanishPanama", DslLang{6154, "Es"} },
  { U"SpanishParaguay", DslLang{15370, "Es"} },
  { U"SpanishPeru", DslLang{10250, "Es"} },
  { U"SpanishProperNames", DslLang{33802, "Es"} },
  { U"SpanishPuertoRico", DslLang{20490, "Es"} },
  { U"SpanishTraditionalSort", DslLang{1034, "Es"} },
  { U"SpanishUruguay", DslLang{14346, "Es"} },
  { U"SpanishVenezuela", DslLang{8202, "Es"} },
  { U"Sunda", DslLang{1635, "Su"} },
  { U"Sutu", DslLang{1072, "--"} },
  { U"Swahili", DslLang{1089, "Sw"} },
  { U"Swazi", DslLang{1636, "Ss"} },
  { U"Swedish", DslLang{1053, "Sv"} },
  { U"SwedishFinland", DslLang{2077, "Sv"} },
  { U"Tabassaran", DslLang{1637, "--"} },
  { U"Tagalog", DslLang{1553, "Tl"} },
  { U"Tahitian", DslLang{1639, "Ty"} },
  { U"Tajik", DslLang{1064, "Tg"} },
  { U"Tajik_Legacy", DslLang{1638, "Tg"} },
  { U"Tamil", DslLang{1097, "Ta"} },
  { U"Tatar", DslLang{1092, "Tt"} },
  { U"Telugu", DslLang{1098, "Te"} },
  { U"Thai", DslLang{1054, "Th"} },
  { U"Tibet", DslLang{1105, "Bo"} },
  { U"Tinpo", DslLang{1640, "--"} },
  { U"Tongan", DslLang{1641, "--"} },
  { U"Tsonga", DslLang{1073, "Ts"} },
  { U"Tswana", DslLang{1074, "Tn"} },
  { U"Tun", DslLang{1642, "--"} },
  { U"Turkish", DslLang{1055, "Tr"} },
  { U"Turkmen", DslLang{1090, "Tk"} },
  { U"TurkmenLatin", DslLang{1656, "Tk"} },
  { U"Turkmen_Legacy", DslLang{1643, "Tk"} },
  { U"Tuvin", DslLang{1644, "Tyv"} },
  { U"Udmurt", DslLang{1645, "Udm"} },
  { U"Uighur", DslLang{1646, "Ug"} },
  { U"UighurCyrillic", DslLang{1646, "Ug"} },
  { U"UighurLatin", DslLang{1647, "Ug"} },
  { U"Ukrainian", DslLang{1058, "Uk"} },
  { U"Universal", DslLang{1653, "--"} },
  { U"UrduIndia", DslLang{2080, "Ur"} },
  { U"UrduPakistan", DslLang{1056, "Ur"} },
  { U"User", DslLang{1554, "--"} },
  { U"UzbekCyrillic", DslLang{2115, "Uz"} },
  { U"UzbekLatin", DslLang{1091, "Uz"} },
  { U"Venda", DslLang{1075, "Ve"} },
  { U"Vietnamese", DslLang{1066, "Vi"} },
  { U"Visayan", DslLang{1648, "--"} },
  { U"Welsh", DslLang{1106, "Cy"} },
  { U"Welsh_Legacy", DslLang{1543, "Cy"} },
  { U"Wend", DslLang{1070, "Sb"} },
  { U"Wolof", DslLang{1160, "Wo"} },
  { U"Wolof_Legacy", DslLang{1649, "Wo"} },
  { U"Xhosa", DslLang{1076, "Xh"} },
  { U"Yakut", DslLang{1157, "Sah"} },
  { U"Yakut_Legacy", DslLang{1650, "Sah"} },
  { U"Yiddish", DslLang{1085, "Yi"} },
  { U"Zapotec", DslLang{1651, "Zap"} },
  { U"Zulu", DslLang{1077, "Zu"} }
};

}

#endif