/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_home_metronomics_AudioEngineNative */

#ifndef _Included_org_home_metronomics_AudioEngineNative
#define _Included_org_home_metronomics_AudioEngineNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_home_metronomics_AudioEngineNative
 * Method:    getAudioData
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT void JNICALL Java_org_home_metronomics_AudioEngineNative_init
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_org_home_metronomics_AudioEngineNative_playSound
  (JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_org_home_metronomics_AudioEngineNative_playPattern
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_org_home_metronomics_AudioEngineNative_stopPattern
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
