/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_home_metronomics_FFTEngineNative */

#ifndef _Included_org_home_metronomics_FFTEngineNative
#define _Included_org_home_metronomics_FFTEngineNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_home_metronomics_FFTEngineNative
 * Method:    getAudioData
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT void JNICALL Java_org_home_metronomics_FFTEngineNative_getFFT
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
