/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_home_metronomics_WavReaderNative */

#ifndef _Included_org_home_metronomics_WavReaderNative
#define _Included_org_home_metronomics_WavReaderNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_home_metronomics_WavReaderNative
 * Method:    getAudioData
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jobject JNICALL Java_org_home_metronomics_WavReaderNative_getAudioData
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
